 "use client";

import { ChatPanel } from "@/components/chat/ChatPanel";
import { TransactionPreview } from "@/components/transaction/TransactionPreview";
import { useState } from "react";
import { useWallet } from "@/context/WalletContext";
import { interpretCommand } from "@/lib/mockAi";

export type Role = "user" | "agent";

export type ChatMessage = {
  id: string;
  role: Role;
  content: string;
  createdAt: number;
};

export type ProposedTransaction = {
  id: string;
  intentType: "send" | "swap" | "stake" | "xcm" | "deposit";
  asset: string;
  amount: string;
  from?: string;
  to?: string;
  network: string;
  summary: string;
  riskLevel: "low" | "medium" | "high";
};

export default function Page() {
  const { address } = useWallet();
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "welcome",
      role: "agent",
      content:
        "Hey, I’m your Polka Pulse agent. Tell me what you want to do with your Polkadot assets and I’ll orchestrate the XCM magic for you.",
      createdAt: Date.now()
    }
  ]);

  const [preview, setPreview] = useState<ProposedTransaction | null>(null);

  const handleSend = async (content: string) => {
    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content,
      createdAt: Date.now()
    };

    setMessages(prev => [...prev, userMessage]);

    const intent = interpretCommand(content);

    const vaultAddress =
      process.env.NEXT_PUBLIC_PULSE_VAULT_ADDRESS ?? "0xYourPulseVaultAddress";

    const agentCopy =
      intent.action === "deposit"
        ? `I’ve parsed this as a deposit of ${intent.amount} ${intent.asset} into your PulseVault. Review the transaction preview before you execute it.`
        : "I’ve parsed your intent and prepared a transaction preview. Review the details on the right and confirm when you’re ready.";

    const agentMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "agent",
      content: agentCopy,
      createdAt: Date.now()
    };

    setMessages(prev => [...prev, agentMessage]);

    setPreview({
      id: crypto.randomUUID(),
      intentType: intent.action,
      asset: intent.asset,
      amount: intent.amount,
      from: address ?? "Your wallet",
      to: vaultAddress,
      network: "Polkadot Hub Testnet",
      summary:
        intent.action === "deposit"
          ? `Deposit ${intent.amount} ${intent.asset} from your connected wallet into PulseVault on Polkadot Hub Testnet using pallet-revive precompiles.`
          : "Execute an intent on your PulseVault via pallet-revive precompiles.",
      riskLevel: "low"
    });
  };

  const handleClearPreview = () => setPreview(null);

  return (
    <div className="grid gap-6 md:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h1 className="text-lg font-semibold tracking-tight text-white">
            Agent Console
          </h1>
          <span className="text-xs text-zinc-400">
            Natural language in · Protocol-grade intents out
          </span>
        </div>
        <ChatPanel messages={messages} onSend={handleSend} />
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-semibold tracking-tight text-white">
            Transaction Preview
          </h2>
          <span className="text-xs text-zinc-400">
            Generated by AI · Executed via Solidity on PVM
          </span>
        </div>
        <TransactionPreview
          preview={preview}
          onClear={handleClearPreview}
        />
      </div>
    </div>
  );
}

